 

// -----------------------------------------------------------------------
// <autogenerated>
//    This code was generated from a template.
//
//    Changes to this file may cause incorrect behaviour and will be lost
//    if the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using BrightstarDB.Client;
using BrightstarDB.EntityFramework;

using System.Text;
using System.Threading.Tasks;

namespace BrightstarDBProjekt 
{
    public partial class MyEntityContext : BrightstarEntityContext {
    	
    	static MyEntityContext() 
    	{
            InitializeEntityMappingStore();
        }
        
        /// <summary>
        /// Initialize the internal cache of entity attribute information.
        /// </summary>
        /// <remarks>
        /// This method is normally invoked from the static constructor for the generated context class.
        /// It is provided as a public static method to enable the use of the cached entity attribute 
        /// information without the need to construct a context (typically in test code). 
        /// In normal application code you should never need to explicitly call this method.
        /// </remarks>
        public static void InitializeEntityMappingStore()
        {
    		var provider = new ReflectionMappingProvider();
    		provider.AddMappingsForType(EntityMappingStore.Instance, typeof(BrightstarDBProjekt.Models.IKorisnik));
    		EntityMappingStore.Instance.SetImplMapping<BrightstarDBProjekt.Models.IKorisnik, BrightstarDBProjekt.Models.Korisnik>();
    		provider.AddMappingsForType(EntityMappingStore.Instance, typeof(BrightstarDBProjekt.Models.IUloga));
    		EntityMappingStore.Instance.SetImplMapping<BrightstarDBProjekt.Models.IUloga, BrightstarDBProjekt.Models.Uloga>();
    	}
    	
    	/// <summary>
    	/// Initialize a new entity context using the specified BrightstarDB
    	/// Data Object Store connection
    	/// </summary>
    	/// <param name="dataObjectStore">The connection to the BrightstarDB Data Object Store that will provide the entity objects</param>
    	public MyEntityContext(IDataObjectStore dataObjectStore) : base(dataObjectStore)
    	{
    		InitializeContext();
    	}
    
    	/// <summary>
    	/// Initialize a new entity context using the specified Brightstar connection string
    	/// </summary>
    	/// <param name="connectionString">The connection to be used to connect to an existing BrightstarDB store</param>
    	/// <param name="enableOptimisticLocking">OPTIONAL: If set to true optmistic locking will be applied to all entity updates</param>
        /// <param name="updateGraphUri">OPTIONAL: The URI identifier of the graph to be updated with any new triples created by operations on the store. If
        /// not defined, the default graph in the store will be updated.</param>
        /// <param name="datasetGraphUris">OPTIONAL: The URI identifiers of the graphs that will be queried to retrieve entities and their properties.
        /// If not defined, all graphs in the store will be queried.</param>
        /// <param name="versionGraphUri">OPTIONAL: The URI identifier of the graph that contains version number statements for entities. 
        /// If not defined, the <paramref name="updateGraphUri"/> will be used.</param>
    	public MyEntityContext(
    	    string connectionString, 
    		bool? enableOptimisticLocking=null,
    		string updateGraphUri = null,
    		IEnumerable<string> datasetGraphUris = null,
    		string versionGraphUri = null
        ) : base(connectionString, enableOptimisticLocking, updateGraphUri, datasetGraphUris, versionGraphUri)
    	{
    		InitializeContext();
    	}
    
    	/// <summary>
    	/// Initialize a new entity context using the specified Brightstar
    	/// connection string retrieved from the configuration.
    	/// </summary>
    	public MyEntityContext() : base()
    	{
    		InitializeContext();
    	}
    	
    	/// <summary>
    	/// Initialize a new entity context using the specified Brightstar
    	/// connection string retrieved from the configuration and the
    	//  specified target graphs
    	/// </summary>
        /// <param name="updateGraphUri">The URI identifier of the graph to be updated with any new triples created by operations on the store. If
        /// set to null, the default graph in the store will be updated.</param>
        /// <param name="datasetGraphUris">The URI identifiers of the graphs that will be queried to retrieve entities and their properties.
        /// If set to null, all graphs in the store will be queried.</param>
        /// <param name="versionGraphUri">The URI identifier of the graph that contains version number statements for entities. 
        /// If set to null, the value of <paramref name="updateGraphUri"/> will be used.</param>
    	public MyEntityContext(
    		string updateGraphUri,
    		IEnumerable<string> datasetGraphUris,
    		string versionGraphUri
    	) : base(updateGraphUri:updateGraphUri, datasetGraphUris:datasetGraphUris, versionGraphUri:versionGraphUri)
    	{
    		InitializeContext();
    	}
    	
    	private void InitializeContext() 
    	{
    		Korisniks = 	new BrightstarEntitySet<BrightstarDBProjekt.Models.IKorisnik>(this);
    		Ulogas = 	new BrightstarEntitySet<BrightstarDBProjekt.Models.IUloga>(this);
    	}
    	
    	public IEntitySet<BrightstarDBProjekt.Models.IKorisnik> Korisniks
    	{
    		get; private set;
    	}
    	
    	public IEntitySet<BrightstarDBProjekt.Models.IUloga> Ulogas
    	{
    		get; private set;
    	}
    	
        public IEntitySet<T> EntitySet<T>() where T : class {
            var itemType = typeof(T);
            if (typeof(T).Equals(typeof(BrightstarDBProjekt.Models.IKorisnik))) {
                return (IEntitySet<T>)this.Korisniks;
            }
            if (typeof(T).Equals(typeof(BrightstarDBProjekt.Models.IUloga))) {
                return (IEntitySet<T>)this.Ulogas;
            }
            throw new InvalidOperationException(typeof(T).FullName + " is not a recognized entity interface type.");
        }
    
        } // end class MyEntityContext
        
}
namespace BrightstarDBProjekt.Models 
{
    
    public partial class Korisnik : BrightstarEntityObject, IKorisnik 
    {
    	public Korisnik(BrightstarEntityContext context, BrightstarDB.Client.IDataObject dataObject) : base(context, dataObject) { }
        public Korisnik(BrightstarEntityContext context) : base(context, typeof(Korisnik)) { }
    	public Korisnik() : base() { }
    	public System.String KorisnikID { get {return GetKey(); } set { SetKey(value); } }
    	#region Implementation of BrightstarDBProjekt.Models.IKorisnik
    
    	public System.String Ime
    	{
            		get { return GetRelatedProperty<System.String>("Ime"); }
            		set { SetRelatedProperty("Ime", value); }
    	}
    
    	public System.String Prezime
    	{
            		get { return GetRelatedProperty<System.String>("Prezime"); }
            		set { SetRelatedProperty("Prezime", value); }
    	}
    
    	public System.String KorisnickoIme
    	{
            		get { return GetRelatedProperty<System.String>("KorisnickoIme"); }
            		set { SetRelatedProperty("KorisnickoIme", value); }
    	}
    
    	public System.String Lozinka
    	{
            		get { return GetRelatedProperty<System.String>("Lozinka"); }
            		set { SetRelatedProperty("Lozinka", value); }
    	}
    
    	public BrightstarDBProjekt.Models.IUloga Uloga
    	{
            get { return GetRelatedObject<BrightstarDBProjekt.Models.IUloga>("Uloga"); }
            set { SetRelatedObject<BrightstarDBProjekt.Models.IUloga>("Uloga", value); }
    	}
    	#endregion
    }
}
namespace BrightstarDBProjekt.Models 
{
    
    public partial class Uloga : BrightstarEntityObject, IUloga 
    {
    	public Uloga(BrightstarEntityContext context, BrightstarDB.Client.IDataObject dataObject) : base(context, dataObject) { }
        public Uloga(BrightstarEntityContext context) : base(context, typeof(Uloga)) { }
    	public Uloga() : base() { }
    	public System.String UlogaID { get {return GetKey(); } set { SetKey(value); } }
    	#region Implementation of BrightstarDBProjekt.Models.IUloga
    
    	public System.String Vrsta
    	{
            		get { return GetRelatedProperty<System.String>("Vrsta"); }
            		set { SetRelatedProperty("Vrsta", value); }
    	}
    
    	public System.String Opis
    	{
            		get { return GetRelatedProperty<System.String>("Opis"); }
            		set { SetRelatedProperty("Opis", value); }
    	}
    	public System.Collections.Generic.ICollection<BrightstarDBProjekt.Models.IKorisnik> Korisnici
    	{
    		get { return GetRelatedObjects<BrightstarDBProjekt.Models.IKorisnik>("Korisnici"); }
    		set { if (value == null) throw new ArgumentNullException("value"); SetRelatedObjects("Korisnici", value); }
    								}
    	#endregion
    }
}
